### PR TITLE
Template improvements (PNG, Exif, DNG, Mach-O, General)

### PR DESCRIPTION
**Pull request by fosterbrereton**
Changes include:

- PNG: subprocs for some chunk types
- PNG: better section values (summaries) for some chunk types
- PNG: use of the new `sectionname` command to improve chunk type naming
- Addition of `Metadata/Exif.tcl`
- Addition of `Images/DNG.tcl`
- Addition of `Executables/Mach-O.tcl`
- Addition of `Utilities/General.tcl` (`proc`s to assist in template evaluation, especially under conditions where the file being evaluated may not be well-formed.)
- ~Addition of `include` command, allowing one template script to include another in its evaluation, to allow for common command and subcomponent reuse.~ (Already merged as #342)

Screenshot of PNG improvements:
Screen Shot 2021-07-13 at 11 20 05 a

Screenshot of Mach-O template output:
Screen Shot 2021-07-15 at 10 29 23 a

### CODE REVIEW

**Comment by fosterbrereton** [comment]
For capabilities like Exif support, it would be really nice to be able to put that in a separate file so multiple templates could leverage it (e.g., PNG, TIFF, PSD, etc.)

**Comment by fosterbrereton** [comment]
I figured out how to include other Tcl scripts. Let me clean this up - this PR isn't quite ready to merge yet.

**Comment by fosterbrereton** [comment]
Not all PNG chunks are fully fleshed out. Even so, this is a good step forward. This PR is ready to merge, pending any commentary / review requests.

**Comment by fosterbrereton** [comment]
@kainjow I'll be working on the Mach-O format for some time, though it needs elements that are a part of this PR which is why I started it here. Feel free to merge what's here if you're comfortable with that, and I can spin up another PR for further changes. Otherwise, I'll keep pushing changes to this PR as I feel they're ready. This one is getting a bit long in the tooth...

**Comment by kainjow** [comment]
thanks. appreciate all the changes, but I think this PR has too many changes. Can you split it out into smaller PRs that are easier to review? Code changes separate from template changes would be good.

**Comment by fosterbrereton** [comment]
That's a fair assessment. I'll split these out into their own PRs, but it will take me some time, as I've got other pressing issues to attend to. I'll come back to this for sure, though.

**Comment by fosterbrereton** [comment]
@kainjow PR #342 contains just the source file changes for the template `include` directive, as well as a couple source code cleanup tweaks. Assuming that PR gets approved, this PR will reduce down to just the templates.

**Comment by fosterbrereton** [comment]
@kainjow I have updated this PR to include the latest changes from `master`. The files in this PR now are just for new file format templates. Please let me know what you think, and thanks for you patience as I get these cleaned up.

**Comment by kainjow** [comment]
Awesome!

**Pull request merged**
