### PR TITLE
✨ execute custom command after saving file

### PR DESCRIPTION
**Pull request by ourfor**
- run custom command after saving file

image

### CODE REVIEW

**Comment by kainjow** [comment]
What’s your use case for this? I’m not sure it’s a fit for Hex Fiend. There are other ways one can trigger actions when a file is written.

**Comment by ourfor** [comment]
> What’s your use case for this? I’m not sure it’s a fit for Hex Fiend. There are other ways one can trigger actions when a file is written.

This modification can be used to re-sign the modified binary or perform other operations. If not needed, you can turn it off with a switch

**Comment by wader** [comment]
Possible to solve with https://github.com/watchexec/watchexec etc?

**Comment by kainjow** [comment]
Closing per my previous comment. Thanks for your understanding.

**Pull request closed without merging**
