### PR TITLE
Implement #346 "Only 'replace' for comparison"

### PR DESCRIPTION
**Pull request by usr-sse2**

### CODE REVIEW

**Comment by usr-sse2** [comment]
Also fixes #360 because @greggman actually wants to compare files that should be identical, so simple byte-to-byte comparison is faster (O(N) vs O(N^2)) and more suitable for this task than the snake algorithm with insert/remove detection.

**Review by InfernalGunner99 — APPROVED** [review]

**Comment by usr-sse2** [comment]
Oops, there is a bug, converting to draft until I fix it

**Comment by ScrelliCopter** [comment]
This is really useful and in most cases is the compare mode I want, I hope this can get merged.

**Comment by usr-sse2** [comment]
@kainjow I see that you've merged #411 and #412, what about this PR? Should I resolve conflicts in `Preferences.xib` or are there any other issues?

**Comment by kainjow** [comment]
Yes resolving conflicts would be helpful.

**Comment by usr-sse2** [comment]
OK, I've resolved the merge conflicts. The last commit is not mandatory, I just prefer to use constraints (Auto Layout) to position the controls properly. The actual control positions are already baked into the previous commit.

**Comment by kainjow** [comment]
Thanks! ya I've neglected to use Auto Layout there since the window isn't resizable nor is it localized. I plan on rewriting it in SwiftUI at some point anyways, which will make diffs much easier.

**Comment by kainjow** [comment]
In e13647f  I changed it so the user defaults calls are done in the app and those settings are passed into the edit class.

**Pull request merged**
