### PR TITLE
Template autodetection

### PR DESCRIPTION
**Pull request by kainjow**

### CODE REVIEW

**Comment by kainjow** [comment]
@Wevah if you're ok with this, I'd like to merge this as a starting point. Want to ensure you get credit.

**Comment by Wevah** [comment]
@kainjow I think I'm okay with it, with the caveat that I haven't looked at the code in quite a while (as you can see!).

**Comment by Wevah** [comment]
Should those incorrect commits relating to syntax coloring be removed?

**Comment by kainjow** [comment]
Seems like it's fine based on the diff, there was a revert. I'll do a squash anyways. And I think I'll merge into a branch, and then do some cleanup.

**Comment by kainjow** [comment]
Merged into master here dc0452fe73a1336f88504e32bc9bea15c9fba1db - thanks!

**Pull request merged**
